name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter (Next.js ESLint)
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint # testet nur nach Linting, wenn du das von der Reihenfolge her brauchst
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Jest)
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: lint # Wenn du zuerst das Linting brauchst
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build] # Dieser Job wird nach den Tests und dem Build ausgeführt
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
